### ISSUE TITLE
Error executing manually built standalone floss executables

### ISSUE THREAD

**Issue by r0ny123** [fireeye/flare-floss#354]
I used `Github Action` to build `FLOSS` executable using build instruction mentioned [here](https://github.com/fireeye/flare-floss/blob/master/doc/installation.md#step-4-building-standalone-executables). However the build succeeded but the built executable resulted into error while running this command `floss --no-static-strings 02179f3ba93663074740b5c0d283bae2.exe_`

The error:
```
C:\Users\Rony\Desktop\dist>floss --no-static-strings 02179f3ba93663074740b5c0d283bae2.exe_
ERROR:floss:Vivisect failed to load the input file: No module named pe
```
However the static strings were extracted correctly.

This is the workflow file I used to build floss:
```
name: Flare-Floss build
on:
  workflow_dispatch:
jobs:
  build-windows:
    name: Build floss Binaries
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: fireeye/flare-floss
      - uses: actions/setup-python@v2
        with: 
          python-version: 2.7
      - name: Install PyInstaller
        run: pip install 'pyinstaller==3.*'
      - name: Install dependencies
        run: pip install pyyaml simplejson tabulate vivisect==0.1.0 plugnplay viv-utils==0.3.17 enum34
      - name: Build Flare-Floss
        run: pyinstaller floss.spec
      - name: Upload Windows compilation output.
        uses: actions/upload-artifact@v2
        with:
          name: flare-floss-latest
          path: "**/dist/"
```
and the floss executable built using latest commit: [floss.zip](https://github.com/fireeye/flare-floss/files/5910474/floss.zip)
